### ISSUE TITLE
Problem after restart

### ISSUE THREAD

**Issue by limer-org** [sigio/sysadmin#3]
We have `monitor.sh` in cron for every 20 minutes. 
After server shutdown, script doesn't execute because:
```
# ./scripts/monitor.sh
cat: /var/run/monitor/pid: No such file or directory
lock failed, PID  is active
```
It seems like script gets KILL signal when shuting and don't removes `/var/run/monitor`
```
# ll /var/run/monitor/
total 0
```

**Comment by limer-org** [comment]
Maybe adding a variable `$OTHERPID` checking whether it has value to solve the problem?

**Comment by sigio** [comment]
On most systems /var/run/ contents is removed at boot (or the filesystem is stored in tmpfs/ram).

**Comment by limer-org** [comment]
We have CentOS 5 i 6. Could you tell me is this correct behavior that does not clear the /var/run ?

**Comment by limer-org** [comment]
OK. CentOS 7 has `/var/run` as tmpfs. We need to come up with a workaround for the problem.
Maybe some patch to work with CentOS 5 or 6 :) ??

**Comment by sigio** [comment]
You could make an @reboot cronjob to remove the /var/run/monitor directory ... though I don't really see in what situation it fails... I'm running it on CentOS 5.x and 6.x as well...  and haven't run into this issue yet.

**Comment by limer-org** [comment]
Thanks for help. We have this script on about 400 servers. Problem occurs when one of servers is not properly closed and at this time script is executing. For example:  because he was suddenly powered off.

**Comment by limer-org** [comment]
I implemented this workoround with @reboot. Thx.
